# Usage: ansible-playbook -K mc-remove.yaml

- hosts: mcservers

  vars:
    base_source_path: /var/games/minecraft/_core/
    base_install_path: /var/games/minecraft/
    serverjar: paper-1.16.5-753.jar

  vars_prompt:
  - name: mcdir
    prompt: Specify server directory title (not the full path)
    private: no
  - name: server_port
    prompt: Specify server port
    private: no

  tasks:

  - name: check that server is listening
    port: "{{ server_port }}

  - name: backup server before removal
    command: "/etc/cron.d/minecraft.sh {{ mcdir }} backup"
    changed_when: false
    tags: backup

  - name: stop minecraft server service$
    service:
      name: "minecraft@{{ mcdir }}"
      state: stopped
      enabled: no
      masked: no
    become: yes

  - name: chedk that server has stopped
    port: "{{ server_port }}"
    delay: 35
    state: drained

  - name: delete host firewall rule for this server
    community.general.ufw:
      delete: yes
      rule: allow
      port: "{{ server_port }}"
      proto: tcp
      comment: "Minecraft Server {{ mcdir }}"
    become: yes
    tags: firewall

  - name: reload firewall with new rules
    community.general.ufw:
      state: reloaded
    become: yes
    tags: firewall

  - name: delete cron job for backups
    ansible.builtin.cron:
      name: "{{ mcdir }} backup"
      minute: "45"
      hour: "03"
      job: "/etc/cron.d/minecraft.sh {{ mcdir }} backup"
      state: absent
    tags: cron

  - name: remove server files
    file:
      state: absent
      path: "{{ base_install_path }}{{ mcdir }}"

