- name: create users and groups
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars:
    uname: minecraft
    ugroup: minecraft
    floc_bash: "/usr/bin/bash"

  vars_prompt:
    name: upass
    prompt: "Enter the password for {{ uname }}"
    unsafe: true

  tasks:

    - name: debug - host variables
      debug:
        var: hostvars[inventory_hostname]
      tags: [never, debug]

    - name: debug - application variables
      debug:
        msg: |
          uname: "{{ uname }}"
          ugroup: "{{ ugroup }}"
      tags: [never, debug]

    - name: create group
      group:
        name: "{{ ugroup }}"
        state: present

    - name: get bash location
      shell:
        cmd: "which bash"
      register: "floc_bash"
      changed_when: false
      tags: [never,bash]

    - name: debug - display bash location
      debug:
        msg: "floc_bash"
      changed_when: false
      tags: [never, debug]

    - name: create user
      user:
        name: "{{ uname }}"
        password: "{{ upass | password_hash('sha512',65534|random(seed=inventory_hostname)|string) }}"
        shell: "{{ floc_bash }}"
        group: "{{ ugroup }}"
        comment: "Minecraft Administrator"
        state: present
        update_password: on_create

    - name: check pubkey integrity
      stat: 
        path: pubkey/authorized_keys
        checksum_algorithm: sha256
        get_checksum: true
      register: result
      failed_when: result.stat.checksum != "21eb1478c4972bcd9d3aae9054117795f2a033bb5366865382c3c9d26f67b067"
      tags: pubkey

    - name: debug - checksum of the authorized_key
      debug: 
        msg: "{{ result }}"
      tags: [never, debug, pubkey]

    - name: install pubkey
      copy:
        src: pubkey/authorized_keys
        dest: "/home/{{ uname }}//.ssh/"
      tags: pubkey

    # Use the --tags=remove options to call just this function to remove a user
    - name: remove user
      user:
        name: "{{ uname }}"
        state: absent
        remove: yes
      tags: [never, remove]

