- name: Check if port 80 is listening
  wait_for:
    port: 80
    delay: 5
    timeout: 10
    msg: "Timeout waiting for 80 to respond"
  register: port_check
  ignore_errors: yes

- name: try to restart service if not listening
  server: name=https state=started enabled=yes
  when: port_check.failed == true
